database:
    mongo:
        user: usrPedidosOnline
        password: Huffman123
        ip: vps-1791261-x.dattaweb.com
        port: 4596
        db: PedidosOnline
server:
     port: 45589
     error:
        include-message: always